### ISSUE TITLE
Gameplay videos with a comma in their name fail to play

### ISSUE THREAD

**Issue by mechevarria** [Wintermute0110/skin.estuary.AEL#2]
Commas seem to break the file path to gameplay videos. Other image assets with commas are fine.  For example:
`Firemen, The (Japan).mp4`

**Comment by mechevarria** [comment]
Found a fix by using the `$ESCINFO` function instead of the `$INFO` function. I will probably fork and setup a pull request soon

**Comment by Wintermute0110** [comment]
Merged you PR. AML includes an option to not render trailers (aka do not create the trailer infolabel) and I will port it to AEL. I will also enable the rendering of trailers in Estuary AEL so users that want to avoid the stuttering can use the `Do not render trailers` option.

**Comment by mechevarria** [comment]
Perfect, closing
